name: Unit and E2E Tests

on:
  push:
    branches:
      - master
      - testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Jest
      run: npm install jest
    - name: Run unit tests (Jest)
      run: npm run jest
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      run: python manage.py migrate
    - name: Start Django server
      run: python manage.py runserver &
      env:
        DJANGO_WEATHER_API_KEY: ${{ secrets.DJANGO_WEATHER_API_KEY }}

    # Install NPM dependencies, cache them correctly
    # and run all Cypress tests
    - name: Run E2E Tests (Cypress)
      uses: cypress-io/github-action@v2
