---
# *Required* The access token for the org that you wish to send metrics to.
hostname: learn-signalfx
signalFxRealm: us1
signalFxAccessToken: {"#from": "signalfx-access-token.txt"}
ingestUrl: {"#from": "signalfx-ingest-url.txt"}
apiUrl: {"#from": "signalfx-api-url.txt"}
cluster: {"#from": "/etc/signalfx/cluster", optional: true}

intervalSeconds: 10

logging:
  # Valid values are 'debug', 'info', 'warning', and 'error'
  level: info

# observers are what discover running services in the environment
observers:
  - type: host

monitors:
  - {"#from": "/etc/signalfx/monitors/*.yaml", flatten: true, optional: true}
  - type: host-metadata
  - type: processlist
  - type: cpu
  - type: filesystems
  - type: disk-io
  - type: net-io
  - type: load
  - type: memory
  - type: vmem
  - type: postgresql
    connectionString: 'sslmode=disable user=learnsignalfx password=learnsignalfx'
