AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Jbb single server: Create a Jbb stack using a single EC2 instance. This
  sample template only works in selected regions. This has been tested on the
  default VPC with Public Subnets.
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: Can contain only ASCII characters.
  InstanceType:
    Description: Jbb EC2 instance type
    Type: String
    Default: t2.small
    AllowedValues:
      - t2.small
      - t2.medium
      - m5.large
    ConstraintDescription: Must be a valid EC2 instance type
Mappings:
  AWSInstanceType2Arch:
    t2.small:
      Arch: HVMG2
    t2.medium:
      Arch: HVMG2
    m5.large:
      Arch: HVMG2
  AWSRegionArch2AMI:
    us-east-1:
      HVMG2: ami-1853ac65
    us-west-1:
      HVMG2: ami-bf5540df
    us-west-2:
      HVMG2: ami-d874e0a0
    eu-west-1:
      HVMG2: ami-3bfab942
    eu-central-1:
      HVMG2: ami-ac442ac3
    ap-southeast-2:
      HVMG2: ami-43874721
Resources:
  JbbInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !FindInMap 
        - AWSRegionArch2AMI
        - !Ref 'AWS::Region'
        - !FindInMap 
          - AWSInstanceType2Arch
          - !Ref InstanceType
          - Arch
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - !Ref JbbSecurityGroup
      KeyName: !Ref KeyName
      Tags:
        - Key: Name
          Value: Jbb
      UserData: !Base64 
        'Fn::Join':
          - ''
          - - '#!/bin/bash -ex'
            - |+

            - |+

            - >-
              curl
              https://raw.githubusercontent.com/mreferre/yelb/master/deployments/platformdeployment/Linux/redis-server.sh
              | bash
            - |+

            - >-
              curl
              https://raw.githubusercontent.com/mreferre/yelb/master/deployments/platformdeployment/Linux/yelb-db.sh
              | bash
            - |+

            - >-
              curl
              https://raw.githubusercontent.com/mreferre/yelb/master/deployments/platformdeployment/Linux/yelb-appserver.sh
              | bash
            - |+

            - >-
              export Jbb_APPSERVER_ENDPOINT=$(curl
              http://169.254.169.254/latest/meta-data/public-hostname)
            - |+

            - >-
              curl
              https://raw.githubusercontent.com/mreferre/yelb/master/deployments/platformdeployment/Linux/yelb-ui.sh
              | bash
  JbbSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable HTTP access via port 80 and SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
Outputs:
  JbbURL:
    Description: URL for newly created single server Jbb instance
    Value: !Join 
      - ''
      - - 'http://'
        - !GetAtt 
          - JbbInstance
          - PublicDnsName
