@startuml
title = The Primary components of ECS
skinparam backgroundColor #ffffff
component Cluster {
    skinparam BackgroundColor transparent
    skinparam componentStyle uml2
    component Service {
        component "Task Definition" {
            component "Container Definition" {

            }
        }
    }
}
@enduml